name: Infra orchestration

on: 
    workflow_dispatch:
        inputs:
            action:
                description: 'Bring the infrastructure up or down'
                required: true
                default: 'destroy'
                type: choice
                options:
                    - apply
                    - destroy
jobs: 
    infra:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
            - name: Run terraform
              run: |
                cd terraform
                terraform init -backend-config="bucket=${{secrets.BUCKET}}" -backend-config="key=${{secrets.KEY}}" -backend-config="region=${{secrets.REGION}}" -backend-config="dynamodb_table=${{secrets.DYNAMODB}}" 
                terraform plan
                terraform ${{inputs.action}} -auto-approve